# .github/workflows/docker.yml
name: Build & Push Docker Images (GHCR)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ts-mern-azure-starter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [backend, frontend]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (enable emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (container driver)
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image vars
        id: vars
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_PREFIX }}-${{ matrix.app }}
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
          echo "SHA_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "BRANCH_TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build & push ${{ matrix.app }} (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.app }}
          file: ./${{ matrix.app }}/Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          sbom: false
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:latest
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.BRANCH_TAG }}
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.SHA_TAG }}
          build-args: |
            ${{ matrix.app == 'frontend' && format('VITE_API_URL={0}', vars.PROD_VITE_API_URL) || '' }}
